export const sprint12QaEn = {
  "offers.controls": "Offer search and filters",
  "offers.search": "Search offers by listing title",
  "offers.status": "Status",
  "offers.category": "Category",
  "offers.sort": "Sort",
  "offers.all": "All",
  "offers.newest": "Newest first",
  "offers.oldest": "Oldest first",
  "offers.amountHigh": "Amount: high to low",
  "offers.amountLow": "Amount: low to high",
  "offers.currencySort": "Amounts are sorted within each currency; no exchange rate is applied.",
  "offers.reset": "Reset filters",
  "offers.noMatches": "No offers match these filters. Try another search or reset filters.",
  "offers.pending": "You already have a pending offer for this listing.",
  "offers.accepted": "Your offer for this listing has already been accepted.",
  "offers.acceptedOther":
    "An offer for this listing has already been accepted. New offers are unavailable.",
  "offers.viewMine": "View my offer",
  "money.precision": "Enter an amount with no more than 2 decimal places.",
  "transactions.notStarted": "Transaction not started",
  "transactions.viewImport": "View import request",
  "listing.preview.published": "This listing is published and visible to the public.",
  "listing.preview.nonPublic": "This listing is currently not visible to the public.",
  "import.validation.currency": "Select a supported currency.",
};
export const sprint12QaAr: Record<keyof typeof sprint12QaEn, string> = {
  "offers.controls": "البحث في العروض وتصفيتها",
  "offers.search": "ابحث في العروض بعنوان الإعلان",
  "offers.status": "الحالة",
  "offers.category": "الفئة",
  "offers.sort": "الترتيب",
  "offers.all": "الكل",
  "offers.newest": "الأحدث أولاً",
  "offers.oldest": "الأقدم أولاً",
  "offers.amountHigh": "المبلغ: من الأعلى للأقل",
  "offers.amountLow": "المبلغ: من الأقل للأعلى",
  "offers.currencySort": "تُرتّب المبالغ داخل كل عملة دون تطبيق سعر صرف.",
  "offers.reset": "إعادة ضبط الفلاتر",
  "offers.noMatches": "لا توجد عروض تطابق الفلاتر. جرّب بحثاً آخر أو أعد ضبط الفلاتر.",
  "offers.pending": "لديك بالفعل عرض قيد الانتظار لهذا الإعلان.",
  "offers.accepted": "تم قبول عرضك لهذا الإعلان بالفعل.",
  "offers.acceptedOther": "تم قبول عرض لهذا الإعلان بالفعل. لا يمكن تقديم عروض جديدة.",
  "offers.viewMine": "عرض عرضي",
  "money.precision": "أدخل مبلغاً لا يتجاوز منزلتين عشريتين.",
  "transactions.notStarted": "لم تبدأ المعاملة",
  "transactions.viewImport": "عرض طلب الاستيراد",
  "listing.preview.published": "هذا الإعلان منشور وظاهر للعامة.",
  "listing.preview.nonPublic": "هذا الإعلان غير ظاهر للعامة حالياً.",
  "import.validation.currency": "اختر عملة مدعومة.",
};
