export const transactionsEn = {
  "transactions.error.INVALID_MONEY_PRECISION":
    "The stored offer has invalid money precision. It has not been changed, and no transaction was created.",
  "transactions.title": "Transactions",
  "transactions.mine": "My transactions",
  "transactions.detail": "Transaction details",
  "transactions.start": "Start transaction",
  "transactions.view": "View transaction",
  "transactions.back": "Back to my transactions",
  "transactions.waitingBuyer": "Waiting for buyer to start transaction",
  "transactions.waitingCustomer": "Waiting for customer to start transaction",
  "transactions.empty": "No transactions yet",
  "transactions.emptyDescription":
    "An accepted offer can be started as a transaction by its buyer or import request owner.",
  "transactions.boundary":
    "This is a local frontend agreement record, not a payment receipt. Payments and escrow are not available yet. No money has been collected or held.",
  "transactions.id": "Transaction ID",
  "transactions.status": "Transaction status",
  "transactions.source": "Source",
  "transactions.source.LISTING_OFFER": "Marketplace listing offer",
  "transactions.source.IMPORT_OFFER": "Custom car import offer",
  "transactions.sourceId": "Source ID",
  "transactions.offerId": "Accepted offer ID",
  "transactions.sourceLink": "View source",
  "transactions.listingUnavailable":
    "Listing unavailable. The original agreement is preserved below.",
  "transactions.importUnavailable":
    "Import request unavailable. The original agreement is preserved below.",
  "transactions.contextError":
    "Source context could not be loaded. The original agreement is preserved below.",
  "transactions.participants": "Participants",
  "transactions.buyer": "Buyer / customer",
  "transactions.seller": "Seller",
  "transactions.dealer": "Dealer / provider",
  "transactions.role": "Your role",
  "transactions.counterpart": "Other participant",
  "transactions.agreement": "Financial agreement",
  "transactions.amount": "Agreed amount",
  "transactions.currency": "Currency",
  "transactions.payment": "Payment",
  "transactions.escrow": "Escrow",
  "transactions.payment.NOT_STARTED": "Payment not started",
  "transactions.escrow.NOT_STARTED": "Escrow not started",
  "transactions.timeline": "Timeline",
  "transactions.created": "Transaction created",
  "transactions.status.AWAITING_PAYMENT": "Awaiting payment",
  "transactions.status.PAYMENT_PROCESSING": "Payment processing",
  "transactions.status.IN_ESCROW": "In escrow",
  "transactions.status.COMPLETED": "Completed",
  "transactions.status.CANCELLED": "Cancelled",
  "transactions.status.FAILED": "Failed",
  "transactions.error.UNAUTHENTICATED": "Please sign in again before starting a transaction.",
  "transactions.error.FORBIDDEN":
    "You do not have access to this transaction or permission to start it.",
  "transactions.error.NOT_FOUND": "Transaction not found.",
  "transactions.error.SOURCE_NOT_FOUND":
    "The source offer or item is unavailable. No transaction was created.",
  "transactions.error.SOURCE_NOT_ACCEPTED": "Only an accepted offer can start a transaction.",
  "transactions.error.INVALID_SOURCE": "The offer does not match the transaction source.",
  "transactions.error.INVALID_AMOUNT": "The agreed amount is invalid. No transaction was created.",
  "transactions.error.INVALID_CURRENCY":
    "The offer currency is unsupported. No transaction was created.",
  "transactions.error.INVALID_PARTICIPANTS":
    "The agreement participants could not be verified. No transaction was created.",
  "transactions.error.STORAGE_READ_FAILED":
    "Transaction data could not be read or is invalid. Stored records have not been cleared.",
  "transactions.error.STORAGE_WRITE_FAILED":
    "The transaction could not be saved. Please retry. No payment was made.",
};
export const transactionsAr: Record<keyof typeof transactionsEn, string> = {
  "transactions.error.INVALID_MONEY_PRECISION":
    "المبلغ المحفوظ في العرض يتجاوز الدقة المسموحة. لم يتم تغييره ولم يتم إنشاء معاملة.",
  "transactions.title": "المعاملات",
  "transactions.mine": "معاملاتي",
  "transactions.detail": "تفاصيل المعاملة",
  "transactions.start": "بدء المعاملة",
  "transactions.view": "عرض المعاملة",
  "transactions.back": "العودة إلى معاملاتي",
  "transactions.waitingBuyer": "بانتظار بدء المشتري للمعاملة",
  "transactions.waitingCustomer": "بانتظار بدء العميل للمعاملة",
  "transactions.empty": "لا توجد معاملات بعد",
  "transactions.emptyDescription": "يمكن للمشتري أو صاحب طلب الاستيراد بدء معاملة من عرض مقبول.",
  "transactions.boundary":
    "هذا سجل اتفاق محلي في الواجهة وليس إيصال دفع. الدفع والضمان المالي غير متاحين بعد. لم يتم تحصيل أو حجز أي أموال.",
  "transactions.id": "معرّف المعاملة",
  "transactions.status": "حالة المعاملة",
  "transactions.source": "المصدر",
  "transactions.source.LISTING_OFFER": "عرض على إعلان في السوق",
  "transactions.source.IMPORT_OFFER": "عرض استيراد سيارة مخصص",
  "transactions.sourceId": "معرّف المصدر",
  "transactions.offerId": "معرّف العرض المقبول",
  "transactions.sourceLink": "عرض المصدر",
  "transactions.listingUnavailable": "الإعلان غير متاح. تفاصيل الاتفاق الأصلي محفوظة أدناه.",
  "transactions.importUnavailable": "طلب الاستيراد غير متاح. تفاصيل الاتفاق الأصلي محفوظة أدناه.",
  "transactions.contextError": "تعذر تحميل سياق المصدر. تفاصيل الاتفاق الأصلي محفوظة أدناه.",
  "transactions.participants": "الأطراف",
  "transactions.buyer": "المشتري / العميل",
  "transactions.seller": "البائع",
  "transactions.dealer": "المعرض / مقدم الخدمة",
  "transactions.role": "دورك",
  "transactions.counterpart": "الطرف الآخر",
  "transactions.agreement": "الاتفاق المالي",
  "transactions.amount": "المبلغ المتفق عليه",
  "transactions.currency": "العملة",
  "transactions.payment": "الدفع",
  "transactions.escrow": "الضمان المالي",
  "transactions.payment.NOT_STARTED": "لم يبدأ الدفع",
  "transactions.escrow.NOT_STARTED": "لم يبدأ الضمان المالي",
  "transactions.timeline": "السجل الزمني",
  "transactions.created": "تم إنشاء المعاملة",
  "transactions.status.AWAITING_PAYMENT": "بانتظار الدفع",
  "transactions.status.PAYMENT_PROCESSING": "جارٍ معالجة الدفع",
  "transactions.status.IN_ESCROW": "في الضمان المالي",
  "transactions.status.COMPLETED": "مكتملة",
  "transactions.status.CANCELLED": "ملغاة",
  "transactions.status.FAILED": "فشلت",
  "transactions.error.UNAUTHENTICATED": "يرجى تسجيل الدخول مجددًا قبل بدء المعاملة.",
  "transactions.error.FORBIDDEN": "ليس لديك صلاحية الوصول إلى هذه المعاملة أو بدئها.",
  "transactions.error.NOT_FOUND": "المعاملة غير موجودة.",
  "transactions.error.SOURCE_NOT_FOUND": "العرض أو العنصر المصدر غير متاح. لم يتم إنشاء معاملة.",
  "transactions.error.SOURCE_NOT_ACCEPTED": "لا يمكن بدء معاملة إلا من عرض مقبول.",
  "transactions.error.INVALID_SOURCE": "العرض لا يتطابق مع مصدر المعاملة.",
  "transactions.error.INVALID_AMOUNT": "المبلغ المتفق عليه غير صالح. لم يتم إنشاء معاملة.",
  "transactions.error.INVALID_CURRENCY": "عملة العرض غير مدعومة. لم يتم إنشاء معاملة.",
  "transactions.error.INVALID_PARTICIPANTS": "تعذر التحقق من أطراف الاتفاق. لم يتم إنشاء معاملة.",
  "transactions.error.STORAGE_READ_FAILED":
    "تعذر قراءة بيانات المعاملات أو أن البيانات غير صالحة. لم يتم مسح السجلات المحفوظة.",
  "transactions.error.STORAGE_WRITE_FAILED":
    "تعذر حفظ المعاملة. يرجى إعادة المحاولة. لم يتم إجراء أي دفع.",
};
