import type { Agency, VehicleListing } from "@/lib/types";

const car1 = "/assets/car-1.jpg";
const car2 = "/assets/car-2.jpg";
const car3 = "/assets/car-3.jpg";
const car4 = "/assets/car-4.jpg";

const images = [car1, car2, car3, car4];

export const mockAgencies: Agency[] = [
  {
    id: "ag1",
    name: "الفهد موتورز",
    rating: 4.8,
    completedDeals: 342,
    vehicleCount: 58,
    verified: true,
    location: "القاهرة",
    since: 2015,
  },
  {
    id: "ag2",
    name: "Nile Auto Group",
    rating: 4.7,
    completedDeals: 289,
    vehicleCount: 47,
    verified: true,
    location: "الجيزة",
    since: 2011,
  },
  {
    id: "ag3",
    name: "Sahara Motors",
    rating: 4.9,
    completedDeals: 512,
    vehicleCount: 92,
    verified: true,
    location: "الإسكندرية",
    since: 2008,
  },
  {
    id: "ag4",
    name: "Delta Cars",
    rating: 4.6,
    completedDeals: 178,
    vehicleCount: 33,
    verified: true,
    location: "المنصورة",
    since: 2018,
  },
];

const baseListings: Omit<VehicleListing, "id" | "images">[] = [
  {
    title: "BMW 530i M Sport",
    make: "BMW",
    model: "530i",
    year: 2023,
    price: 2450000,
    currency: "EGP",
    mileage: 12000,
    location: "القاهرة",
    condition: "used",
    fuel: "gasoline",
    transmission: "automatic",
    sellerType: "agency",
    sellerId: "ag1",
    sellerName: "الفهد موتورز",
    verified: true,
    featured: true,
    createdAt: "2026-06-01",
  },
  {
    title: "Mercedes-Benz C200 AMG Line",
    make: "Mercedes",
    model: "C200",
    year: 2024,
    price: 3100000,
    currency: "EGP",
    mileage: 0,
    location: "الجيزة",
    condition: "new",
    fuel: "gasoline",
    transmission: "automatic",
    sellerType: "agency",
    sellerId: "ag2",
    sellerName: "Nile Auto Group",
    verified: true,
    featured: true,
    createdAt: "2026-06-04",
  },
  {
    title: "Toyota Corolla XLI",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    price: 720000,
    currency: "EGP",
    mileage: 45000,
    location: "الإسكندرية",
    condition: "used",
    fuel: "gasoline",
    transmission: "automatic",
    sellerType: "individual",
    sellerId: "u1",
    sellerName: "أحمد م.",
    verified: false,
    featured: false,
    createdAt: "2026-06-07",
  },
  {
    title: "Hyundai Tucson GLS",
    make: "Hyundai",
    model: "Tucson",
    year: 2023,
    price: 1180000,
    currency: "EGP",
    mileage: 22000,
    location: "القاهرة",
    condition: "used",
    fuel: "gasoline",
    transmission: "automatic",
    sellerType: "agency",
    sellerId: "ag3",
    sellerName: "Sahara Motors",
    verified: true,
    featured: true,
    createdAt: "2026-06-09",
  },
  {
    title: "Kia Sportage EX",
    make: "Kia",
    model: "Sportage",
    year: 2024,
    price: 1490000,
    currency: "EGP",
    mileage: 0,
    location: "المنصورة",
    condition: "new",
    fuel: "hybrid",
    transmission: "automatic",
    sellerType: "agency",
    sellerId: "ag4",
    sellerName: "Delta Cars",
    verified: true,
    featured: false,
    createdAt: "2026-06-10",
  },
  {
    title: "Nissan Sunny Super Salon",
    make: "Nissan",
    model: "Sunny",
    year: 2021,
    price: 540000,
    currency: "EGP",
    mileage: 62000,
    location: "القاهرة",
    condition: "used",
    fuel: "gasoline",
    transmission: "manual",
    sellerType: "individual",
    sellerId: "u2",
    sellerName: "محمد س.",
    verified: false,
    featured: false,
    createdAt: "2026-06-11",
  },
  {
    title: "Audi Q5 Quattro",
    make: "Audi",
    model: "Q5",
    year: 2023,
    price: 3450000,
    currency: "EGP",
    mileage: 8000,
    location: "القاهرة",
    condition: "used",
    fuel: "gasoline",
    transmission: "automatic",
    sellerType: "agency",
    sellerId: "ag1",
    sellerName: "الفهد موتورز",
    verified: true,
    featured: true,
    createdAt: "2026-06-12",
  },
  {
    title: "MG ZS 1.5",
    make: "MG",
    model: "ZS",
    year: 2024,
    price: 780000,
    currency: "EGP",
    mileage: 0,
    location: "الجيزة",
    condition: "new",
    fuel: "gasoline",
    transmission: "automatic",
    sellerType: "agency",
    sellerId: "ag2",
    sellerName: "Nile Auto Group",
    verified: true,
    featured: false,
    createdAt: "2026-06-13",
  },
];

export const mockListings: VehicleListing[] = baseListings.map((l, i) => ({
  ...l,
  id: `v${i + 1}`,
  images: images.map((url, imageIndex) => ({
    id: `m${i}-${imageIndex}`,
    url: images[(i + imageIndex) % images.length],
    alt: `${l.title} ${imageIndex + 1}`,
  })),
  updatedAt: i % 2 === 0 ? "2026-06-15" : l.createdAt,
  engine: l.fuel === "electric" ? "Electric motor" : i % 2 === 0 ? "2.0 L" : "1.6 L",
  bodyType: ["Sedan", "SUV", "Sedan", "SUV"][i % 4],
  color: ["Black", "White", "Silver", "Blue"][i % 4],
  vin: `SD${String(i + 1).padStart(15, "0")}`,
  stockId: `SD-${String(i + 1).padStart(5, "0")}`,
  views: 180 + i * 73,
}));

export const mockBrands = [
  "BMW",
  "Mercedes",
  "Toyota",
  "Hyundai",
  "Kia",
  "Nissan",
  "Audi",
  "MG",
  "Honda",
  "Chevrolet",
  "Peugeot",
  "Renault",
];

export const mockStats = {
  listings: 12480,
  agencies: 214,
  deals: 8340,
  users: 56000,
};

export const mockTestimonials = [
  {
    id: "t1",
    author: "سارة ع.",
    role: "مشترية",
    quote: "اشتريت سيارتي بأمان تام والدفع كان محمي بالضمان. تجربة ممتازة.",
  },
  {
    id: "t2",
    author: "خالد م.",
    role: "بائع",
    quote: "بعت سيارتي خلال أسبوع فقط، والمنصة سهلة جداً.",
  },
  {
    id: "t3",
    author: "Nour A.",
    role: "Buyer",
    quote: "The escrow made me feel completely safe buying my first car online.",
  },
];

export const mockFaqs = [
  {
    q: "كيف يعمل الدفع الآمن؟",
    a: "أموالك محفوظة في حساب ضمان حتى استلامك للسيارة والتأكد من مطابقتها للمواصفات.",
  },
  {
    q: "ما الفرق بين البائع الفردي والوكيل؟",
    a: "الوكلاء معتمدون وموثقون وتخضع منشآتهم للتحقق، بينما الأفراد يبيعون سياراتهم الشخصية مباشرة.",
  },
  {
    q: "كم يستغرق طلب الاستيراد الخاص؟",
    a: "يعتمد على البلد ونوع السيارة، عادة بين 4 و12 أسبوعاً بعد قبول العرض.",
  },
  {
    q: "هل يمكنني إلغاء الصفقة؟",
    a: "نعم، يمكن استرداد الأموال المحفوظة في الضمان وفق شروط الحماية قبل الإفراج عنها.",
  },
];
