// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/account/profile" | "/auth/forgot-password" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/c2c" | "/compare" | "/contact" | "/dealer-account" | "/dealers" | "/dealers/[id]" | "/favorites" | "/how-it-works" | "/import" | "/vehicles" | "/vehicles/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/auth"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/account/profile": {}
  "/auth": {}
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/c2c": {}
  "/compare": {}
  "/contact": {}
  "/dealer-account": {}
  "/dealers": {}
  "/dealers/[id]": { "id": string; }
  "/favorites": {}
  "/how-it-works": {}
  "/import": {}
  "/vehicles": {}
  "/vehicles/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/auth": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
